### PR TITLE
Fix autompg wine data typo

### PR DESCRIPTION
**Pull request by jrbourbeau**
### Description

Fixes typos in documentation for wine and autompg datasets

### Related issues or pull requests

Fixes issue [#165](https://github.com/rasbt/mlxtend/issues/165)

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks for the PR, @jrbourbeau ! Could you please modify the PR that only the affected files are included, i.e., `docs/sources/user_guide/data/autompg_data.ipynb` and `docs/sources/CHANGELOG.md`. 

I think what happened was that you had older fork of mlxtend, and you ran `git add .` so that you added a bunch of old files to the commit. Since that's a common annoyance for someone committing to open source projects, (I also have this issue very frequently), I added a section on syncing an existing fork here, if it helps: http://rasbt.github.io/mlxtend/contributing/#syncing-an-existing-fork

**Comment by rasbt** [comment]
Also, if that's too complicated to fix this PR, please don't hesitate to make a new PR, where you only use 

```
git add docs/sources/user_guide/data/autompg_data.ipynb
git add docs/sources/CHANGELOG.md 
git commit -m 'fix typos in AutoMPG data documentation'

```

**Comment by jrbourbeau** [comment]
I started from the master branch, but am now trying to add to the updatedocs branch. Maybe that was the issue (not 100% sure)? Would it be best to PR to the master branch, or start from the updatedocs branch and PR to that? Thanks!

**Comment by rasbt** [comment]
Hm, not sure what was going on then. Typically, you would  get the most recent master branch (e.g., by syncing your for if it's not a fresh fork), create a new branch locally, and then push your changes to your fork upstream. Then, GitHub should display a button that allows you to merge your feature branch with the original master branch at rasbt/mlxtend

**Comment by jrbourbeau** [comment]
Oh, okay. When I went to do this pull request, there was a message that I interpreted as saying not to PR into the original master branch at rasbt/mlxtend, but into a topic branch (in this case I chose to PR to updatedocs). I'll make a new PR into the original master branch at rasbt/mlxtend.

**Comment by rasbt** [comment]
Sorry about that confusion. Was it a github message or sth in the docs here, which could be clarified? Probably it meant to say that changes shouldn't be made directly to your copy of the master branch but to a feature  branch which is then to be merged with the "origina" master branch.

**Comment by jrbourbeau** [comment]
When I clicked to make a new PR, there was a default prompt filled in. It starts out like this 
```
<!--
Make sure that you submit this pull request as a separate topic branch (and not to "master")
-->

<!-- Provide a small summary describing the Pull Request below -->

### Description

Fixes typos in documentation for wine and autompg datasets

### Related issues or pull requests

<!-- Please provide a link to the respective issue on the [Issue Tracker](https://github.com/rasbt/mlxtend/issues) if one exists. E.g.,

Fixes #<ISSUE_NUMBER> -->
```

The part of the message that led to my confusion is "Make sure that you submit this pull request as a separate topic branch (and not to "master")". I thought that meant don't submit to the original master branch, but it must meant to make a feature branch in my copy, make changes, and then PR into the original master branch

**Comment by jrbourbeau** [comment]
I just made a new PR from my feature branch into the original master branch. Hopefully that will only have the files that were affected by the update

**Comment by rasbt** [comment]
> When I clicked to make a new PR, there was a default prompt filled in. It starts out like this

Thanks for the note :) , I will clarify that in #168

**Comment by rasbt** [comment]
Thanks for the new PR, I will close this PR now to avoid confusion

**Pull request closed without merging**
