### PR TITLE
Add how-to install using conda

### PR DESCRIPTION
**Pull request by japborst**
Description

A small improvement to help out conda users to easily install mlxtend

Related issues or pull requests

Relates to #143, as mlxtend is now available through conda-forge

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks, I have this info in the web documentation (http://rasbt.github.io/mlxtend/installation/) but it would be good to also have it in the main README. I noticed that the unit tests are failing and I think it's due to the recent sklearn 0.19 release last week. I will make the adjustments regarding CI first, and get back to this PR then. Thanks

**Comment by rasbt** [comment]
One little request, could you move the "Conda" section below the "PyPI" section. Also, the next git commit/push should resolve the unit testing issues, just fixed it. Thanks!

**Comment by japborst** [comment]
@rasbt done! :)

**Comment by rasbt** [comment]
Thanks a lot!

**Pull request merged**
