### PR TITLE
Refactors travis installs to use setup.py

### LINKED ISSUE #305: Refactor travis setup to use `setup.py`
Use the setup.py file for the pip installs in travis, to test if all requirements are met, as suggested in #304

### PR DESCRIPTION
**Pull request by jrbourbeau**
### Description

This PR refactors the installation process run on Travis to use `setup.py` to ensure that all the necessary requirements are included in `setup.py`. 

### Related issues or pull requests

Fixes #305

### Pull Request requirements

- [ ] Added appropriate unit test functions in the `./mlxtend/*/tests` directories
- [ ] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass
- [ ] Checked the test coverage by running `nosetests ./mlxtend --with-coverage`
- [ ] Checked for style issues by running `flake8 ./mlxtend`
- [ ] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file
- [ ] Modify documentation in the appropriate location under `mlxtend/docs/sources/` (optional)
- [ ] Checked that the Travis-CI build passed at https://travis-ci.org/rasbt/mlxtend

### CODE REVIEW

**Comment by jrbourbeau** [comment]
@rasbt after comparing the Travis tests for this PR and those from the latest master branch build (https://travis-ci.org/rasbt/mlxtend/builds/356038365), I think this PR is refactoring the installs on Travis to use `setup.py` for dependency installation correctly. Any issues you see or comments?

**Comment by rasbt** [comment]
Thanks for the PR! 

> pip install ".[testing]"

What exactly does that do?

Also I was thinking it would be good to include a line

    python -c "import mlxtend; print('mlxtend %s' % mlxtend.__version__)"

at the end of the install script, to check that mlxtend was really installed.

**Comment by jrbourbeau** [comment]
`pip install .` installs the local version of `mlxtend` on Travis (along with all the dependencies specified in `requirements.txt`). The `[testing]` part makes sure the extra testing dependencies (i.e. `nose`) are also installed. 

https://github.com/rasbt/mlxtend/blob/744012e6696ec90f667e0f7166cf67ecfc729c66/setup.py#L36-L37

I thought `pip install ".[testing]"` was a little cleaner than 

```
pip install .
pip install nose
```

but that may not be the case. 

> Also I was thinking it would be good to include a line
>
> > python -c "import mlxtend; print('mlxtend %s' % mlxtend.__version__)"
>
>at the end of the install script, to check that mlxtend was really installed.

Totally agree, I'll add it!

**Comment by rasbt** [comment]
> The [testing] part makes sure the extra testing dependencies (i.e. nose) are also installed.

Oh I see! Didn't know about that part, but it makes total sense then! I think that looks pretty good now, overall, once the CI tests pass, it should be good to merge

**Comment by rasbt** [comment]
Will merge it now. Thanks for the work on this PR and the refactoring!

**Comment by jrbourbeau** [comment]
Thanks!

**Pull request merged**
