### PR TITLE
added collinearity_guard parameter and functionality to StackedCVClas…

### PR DESCRIPTION
**Pull request by soumyadsanyal**
…sifier

### Description

Insert Description Here

### Related issues or pull requests

Link related issues/pull requests here

### Pull Request requirements

- [ ] Added appropriate unit test functions in the `./mlxtend/*/tests` directories
- [ ] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass
- [ ] Checked the test coverage by running `nosetests ./mlxtend --with-coverage`
- [ ] Checked for style issues by running `flake8 ./mlxtend`
- [ ] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file
- [ ] Modify documentation in the appropriate location under `mlxtend/docs/sources/` (optional)
- [ ] Checked that the Travis-CI build passed at https://travis-ci.org/rasbt/mlxtend

### CODE REVIEW

**Comment by soumyadsanyal** [comment]
WIP, please don't merge yet!

**Comment by soumyadsanyal** [comment]
Still WIP.

**Comment by soumyadsanyal** [comment]
Tests to come.

**Comment by rasbt** [comment]
Oh yeah, no worries, I won't merge until you think it's ready :). Thanks for the contribution!

**Comment by soumyadsanyal** [comment]
👍 (Also the -1, None, n, random options to come.)

**Pull request closed without merging**
