### PR TITLE
Corrected typos in ExhaustiveFeatureSelection section of the userguide

### LINKED ISSUE #388: Typo in User guide: Section- Exhaustive Feature Selection
The first sentence following **Example 3 Exhaustive Feature Selection for Regression** reads as follows...

> Similar to the classification examples above, the `SequentialFeatureSelector` also supports scikit-learn's estimators for regression.

Should be `ExhaustiveFeatureSelector` instead of `SequentialFeatureSelector`

### PR DESCRIPTION
**Pull request by hvgazula**
### Pull Request Checklist

- [ ] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [ ] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [ ] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [ ] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `nosetests ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [ ] Checked for style issues by running `flake8 ./mlxtend`

### CODE REVIEW

**Comment by hvgazula** [comment]
Didn't follow the protocol laid out in http://rasbt.github.io/mlxtend/contributing/

**Comment by hvgazula** [comment]
Didn't follow protocol laid out in http://rasbt.github.io/mlxtend/contributing/

**Comment by rasbt** [comment]
Hi there! Thanks for the PR!

> Closing pull request. Didn't follow the protocol laid out in http://rasbt.github.io/mlxtend/contributing/

No worries, please feel free to reopen this PR. You can make any number of commits you like -- they will be squashed upon merging anyways (so don't worry about creating temporary "clutter").
Also, for things like typo fixes, what you already submitted looks sufficient to me!

**Comment by rasbt** [comment]
Thanks!

**Pull request merged**
