### PR TITLE
Full pyproject conversion

### PR DESCRIPTION
**Pull request by jmahlik**
### Description
Continuing on the conversation from https://github.com/rasbt/mlxtend/issues/1062.  Converted all the way to a pyproject. This is really slick. Everything builds and installs as expected. The `__version__` thing is no longer a problem. If it's changed in the `__init__.py`, it is picked up automatically.

Was able to delete the `setup.py` and `setup.cfg` entirely by moving the pytest config and the setuptools wheel config. The "universal" wheel section in the `setup.cfg` was causing it to make python 2 compatible wheels (with `py2-py3-non-any.whl`). Now it just makes a `py3` wheel.

Let me know thoughts. Happy to make any changes. The PR is coming from a github org so you might not be able to edit it directly. 

Alternative to #1064 

Build output:

```
python -m build
...
Successfully built mlxtend-0.23.0.dev0.tar.gz and mlxtend-0.23.0.dev0-py3-none-any.whl

ls -l ./dist
mlxtend-0.23.0.dev0.tar.gz
mlxtend-0.23.0.dev0-py3-none-any.whl

# Now change the version to 500 in the __init__.py
python -m build
...
Successfully built mlxtend-500.0.0.tar.gz and mlxtend-500.0.0-py3-none-any.whl
```

### Related issues or pull requests

Fixes https://github.com/rasbt/mlxtend/issues/1062

### Pull Request Checklist

- [x] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [x] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [x] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [x] Ran `PYTHONPATH='.' pytest ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `PYTHONPATH='.' pytest ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [x] Checked for style issues by running `flake8 ./mlxtend`

### CODE REVIEW

**Comment by jmahlik** [comment]
The only thing I could fit in was the long description. But the readme can take its place if that's acceptable.

**Comment by jmahlik** [comment]
I'll close out https://github.com/rasbt/mlxtend/pull/1064 if you like this one better.

**Comment by rasbt** [comment]
Could you try to update the branch by pulling or rebasing from master? The CI should be fixed now.

**Comment by jmahlik** [comment]
Rebased it

**Review by rasbt — APPROVED** [review]

**Comment by rasbt** [comment]
It seems to work now. Thanks a lot for this great PR and restructuring. I will make a PyPI release later today.

**Pull request merged**
