### PR TITLE
Move to nanmean instead of mean

### PR DESCRIPTION
**Pull request by mrkaiser**
Moving to nanmean allows the use of scorers that return nan without breaking existing functionality

### Description

Moved the means to `np.nanmean` to support scorers that may implement returning 

### Related issues or pull requests

Link related issues/pull requests here

### Pull Request requirements

- [x] Added appropriate unit test functions in the `./mlxtend/*/tests` directories
- [x] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass
- [x] Checked the test coverage by running `nosetests ./mlxtend --with-coverage`
- [x] Checked for style issues by running `flake8 ./mlxtend`
- [x] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file
- [x] Modify documentation in the appropriate location under `mlxtend/docs/sources/` (optional)
- [x] Checked that the Travis-CI build passed at https://travis-ci.org/rasbt/mlxtend

### CODE REVIEW

**Comment by mrkaiser** [comment]
The build is failing due to an issue with `sudo apt-get update`

**Comment by rasbt** [comment]
Thanks for the PR, and sorry about the issues with travis-ci  -- I never had any issues with that and it worked up to last weekend. Hm, maybe they changed sth this week. I will look into that and let you know when it's resolved.

**Comment by rasbt** [comment]
Not sure why this issue occurred. I send in a PR for testing and it worked fine. Maybe, it was a temporary issue with the "trusty" environments on their side -- they changed something last week according to their blog. In any case, I removed the trusty flag (I think it was needed back then for the tensorflow code), and it should work fine now. Could you try again? (maybe with a tiny edit like a whitespace or sth like that)

**Comment by mrkaiser** [comment]
@rasbt I have updated the builds and all checks are passing

**Comment by rasbt** [comment]
That's awesome, thanks for the PR!

**Pull request merged**
