### PR TITLE
Colorblind-friendly decision regions

### LINKED ISSUE #347: Colorblind-friendly decision region plots
Right now, the decision region plots are using red and blue colors, which are in this combination not color blind-friendly and should be addressed. I would welcome any feedback and suggestions for optimal color choices

### PR DESCRIPTION
**Pull request by rasbt**
### Description

Modification to the `plot_decision_region` function that makes it easier for color blind people to distinguish between the different decision regions by using the matplotlib 2.0 color panel and solid decision boundary lines.

### Related issues or pull requests

Fixes #347

### Pull Request requirements

- [x] Added appropriate unit test functions in the `./mlxtend/*/tests` directories
- [x] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass
- [x] Checked the test coverage by running `nosetests ./mlxtend --with-coverage`
- [x] Checked for style issues by running `flake8 ./mlxtend`
- [x] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file
- [x] Modify documentation in the appropriate location under `mlxtend/docs/sources/` (optional)
- [ ] Checked that the Travis-CI build passed at https://travis-ci.org/rasbt/mlxtend

### CODE REVIEW

**Comment by rasbt** [comment]
Below are two example plots. I think the "new" matplotlib default color palette is visually pleasing and according to Coblis, it might be more color blind-friendly. However, I think the transparency is still a bit of an issue with regard to color blindness; thus, adding solid decision boundary lines (in black) might help.

unknown-3
unknown-2

**Comment by rasbt** [comment]
Just made the lines a bit thinner. I think this looks fine now :) 
unknown-1

**Comment by jrbourbeau** [comment]
I like the line idea! Was about to comment that a thinner line might look better, but it looks like you just updated to a thinner line 👍

**Comment by rasbt** [comment]
Thanks for the feedback! According to a conversation on twitter, the colors are also distinguishable now. I think this should be good to merge

**Pull request merged**
