### PR TITLE
adding version to iris dataset

### PR DESCRIPTION
**Pull request by janismdhanbad**
### Description

An enhancement of currently existing iris_data function. It gives Iris data R (paper) version and UCI version as both the versions are different.

### Related issues or pull requests
#535 

### Pull Request Checklist

- [x] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [x] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [x] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [x] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `nosetests ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [x] Checked for style issues by running `flake8 ./mlxtend`

### CODE REVIEW

**Comment by rasbt** [comment]
That looks awesome, thanks a lot! In addition, could you add a unit test to the data/tests/ folder to ensure that it works as expected? i.e., `data/tests/test_iris.py`

**Comment by janismdhanbad** [comment]
Thanks! Will create a unit test for it.

**Comment by rasbt** [comment]
Thanks a lot! I think the unit test would have been always true because of the parentheses and evaluating all array elements. I made some changes using numpy's array comparison function (along with some other minor changes in the wording). Otherwise, this PR looks great. Thanks a lot!

**Comment by janismdhanbad** [comment]
Thanks for the changes. Will keep in mind numpy.testing module while testing numpy arrays.

**Pull request merged**
