### PR TITLE
Updated subscripts

### PR DESCRIPTION
**Pull request by olivertomic**
### Description
Fixing small LaTeX subscript issues in documentation for SequentialFeatureSelector class.

### Pull Request Checklist

- [ ] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [ ] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [x] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [ ] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `nosetests ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [ ] Checked for style issues by running `flake8 ./mlxtend`

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks a lot! 

These will be automatically updated on the website with the new version release (planning on doing a new release ~ end of July)

**Comment by olivertomic** [comment]
My pleasure! Looking forward to the new version release. I will use MLextend quite a bit in my machine learning lectures this autumn.

**Comment by rasbt** [comment]
Wow, that's nice to hear! Regarding the next release, I also (finally!) experimented with the "projects" feature on GitHub a bit yesterday and listed the little things that should make it into the next release. There are not many though :) https://github.com/rasbt/mlxtend/projects/1

**Comment by olivertomic** [comment]
Thanks for the information! Quite a few new things to get into ... at least for me. :-)

**Pull request merged**
