### PR TITLE
Adding Multiprocessing feature

### LINKED ISSUE #804: Add a parameter to `plot_decision_regions` for creating rougher but faster plots
For quick prototyping, it might be desirable to have an option to make rougher decision region plots. See the discussion in #801

### PR DESCRIPTION
**Pull request by Ne-oL**
### Description

 This update to the code allows the plot of Decision Regions to be executed on all available cores, in addition there an option to implement it on cluster-wide nodes using the 'ray' parameter in the calling. 
I'm not a programmer by profession so I'm sure my implementation is not pythonic and probably needs a lot of work. so I hope the maintainer can modify or take inspiration of my implementation in case it can't be merged with the main branch as it is.

I found that the speed bottleneck for the decision_regions drawing was due to the slow prediction. to fix it, I added parallelization and distributed the iterative prediction on all available CPUs (local ). I have tested the changes and so far there doesn't seem to be any issues. the speed gain i measured on a small dataset was 21X the original (449 seconds vs 21 seconds on local HPC instance of 36 cores). the large dataset >9,000 input took days(>5 days) to draw, now its taking ~12 minutes on a HPC Cluster (72CPUs). its not their intended goal but it basically addresses issues #801, #804  

### Related issues or pull requests

 Fixes #804, #801

### Pull Request Checklist

- [ ] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [ ] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [ ] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [ ] Ran `PYTHONPATH='.' pytest ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `PYTHONPATH='.' pytest ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [ ] Checked for style issues by running `flake8 ./mlxtend`

### CODE REVIEW

**Comment by rasbt** [comment]
Wow thanks for this! I've been out of office and am a bit tied up right now, but I am looking forward to reviewing this PR. Sounds super awesome and promising. Thanks for submitting this!

**Comment by Ne-oL** [comment]
sorry i was busy and didn't have the time to work on it in the weekend. here is a summary of what's been done:
- I fixed all the issues and the package seems to be working fine now.
- working with Multiprocessing module complicated the code a bit as the "parallel" function could not be used inside the plotting function (mp can only pickle top funcs) so i had to pass any needed variables as parameters. (this could be alleviated if another parallelization library was used like Multiprocess or ray).
- created xtype variable to pass the X.dtype output instead of passing X as a whole.
- Logically n_jobs default  should be 1, but i kept the n_jobs default as "None" to follow Scikit-learn API, changing the variable value late to one inside the function, its ugly but it keeps the API consistent to any users. 

As you can see, there are several opinionated choices in the code, however, as i mentioned before I'm not a programmer so my choices are just what seems logical to me (and not necessarily the best or the pythonic way) so please feel free to change it as you see fit.

**Comment by rasbt** [comment]
I am super sorry about this! I must have been out during the holidays when this PR landed, and I am just seeing this now! Thanks for your work on this, and I am definitely excited to merge this into mlxtend before the next version release!

**Comment by rasbt** [comment]
I think this was a bit messy since you made the changes in master, but no worries. This is a fantastic PR btw. Thanks a lot!

**Comment by Ne-oL** [comment]
Sorry about the noob mistake of making changes directly in master, its my first PR in all honesty. is there a way to easily rectify it? and sorry for troubling you with the linter and formatting issues. i didn't know how to do it and just forgot about it with ongoing research. I'm unsure if there is anything extra on my end required to complete the merge or its all up to you now?

**Pull request merged**
