### PR TITLE
Add decision function method for stacking classifiers

### PR DESCRIPTION
**Pull request by qiagu**
### Pull Request Checklist

- [x] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [x] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [x] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [x] Ran `PYTHONPATH='.' pytest ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `PYTHONPATH='.' pytest ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [x] Checked for style issues by running `flake8 ./mlxtend`

### CODE REVIEW

**Comment by qiagu** [comment]
The roc_auc score calculated in scikit-learn v0.20.3 is different from the one in v0.21.3. I couldn't figure out what parameter caused the discrepancy.

**Comment by rasbt** [comment]
Thanks for the PR. Looks pretty good so far!

Regarding 

> The roc_auc score calculated in scikit-learn v0.20.3 is different from the one in v0.21.3. I couldn't figure out what parameter caused the discrepancy.

I found this in the changelog (https://scikit-learn.org/dev/whats_new/v0.21.html#sklearn-svm):

Screen Shot 2019-11-24 at 9 58 11 PM

Maybe you can 

1. add a new test for `SVC(... decision_function_shape='ovo')`
2. change the current test such that it only runs in sklearn > 0.21.3

E.g.,

```python
from distutils.version import LooseVersion as Version
from sklearn import __version__ as sklearn_version
...

def test ...():
    # test code
    if Version(sklearn_version) > Version("0.21.3"):
        assert ...
    else:
        assert ...
```

**Comment by qiagu** [comment]
@rasbt Thanks. You suggestion always makes the most sense. I stop trying other things.

**Comment by qiagu** [comment]
@rasbt  Do we need to care about the minor decrease of test coverage?

**Comment by rasbt** [comment]
> @rasbt Do we need to care about the minor decrease of test coverage?

No worries, that's fine. The change is so small that it is basically non-existent. I am currently a bit swamped with deadlines but let me go over the code again carefully on the upcoming weekend. Thanks for the PR so far!

**Comment by rasbt** [comment]
Looks great! I just added some examples to the jupyter notebook. Once the test passed, it should be good to merge. Many thanks!

**Comment by qiagu** [comment]
Thanks for merging. @rasbt

**Pull request merged**
