### PR TITLE
Lift feature

### PR DESCRIPTION
**Pull request by bbardakk**
### Description
Lift score is implemented and added under mlxtend.evaluate. 
### Related issues or pull requests

 65

Link related issues/pull requests here: https://github.com/rasbt/mlxtend/issues/65

### Pull Request requirements

- [x] Added appropriate unit test functions in the `./mlxtend/*/tests` directories
- [x] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass
- [x] Checked the test coverage by running `nosetests ./mlxtend --with-coverage`
- [x] Checked for style issues by running `flake8 ./mlxtend`
- [x] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file
- [ ] Modify documentation in the appropriate location under `mlxtend/docs/sources/` (optional)
- [x] Checked that the Travis-CI build passed at https://travis-ci.org/rasbt/mlxtend

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks a lot for the PR, Batuhan, really appreciate it! I will try to give it at more detailed look tomorrow for a test drive and more feedback. 

At a quick glance, I just saw that one of the travis tests failed. It think it's due to Python 2's integer division. E.g., in the lines
where you have `... / ... .shape[0]`. If you could change it to `... / float(... .shape[0])` it should work.

**Comment by bbardakk** [comment]
Hi Sebastian, 

I fixed the zero division problem, thanks for your warning! I'm waiting your feedback for tomorrow, have a good night.

**Comment by rasbt** [comment]
Hm, maybe there was something else going on regarding the failing tests ... Just see that you closed the PR, may I ask why? And please don't worry about too many failing tests, I am happy to take a look and help debugging. Unfortunately, I can't see the travis logs since the PR is closed, would you mind reopening it?

**Comment by rasbt** [comment]
ah never mind, just see you submitted #136 ;)

**Pull request closed without merging**
