### PR TITLE
Lift score

### PR DESCRIPTION
**Pull request by bbardakk**
### Description

Lift score is added.

### Related issues or pull requests

 65

Link related issues/pull requests here
https://github.com/rasbt/mlxtend/issues/65

### Pull Request requirements

- [x] Added appropriate unit test functions in the `./mlxtend/*/tests` directories
- [x] Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass
- [x] Checked the test coverage by running `nosetests ./mlxtend --with-coverage`
- [x] Checked for style issues by running `flake8 ./mlxtend`
- [x] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file
- [x] Modify documentation in the appropriate location under `mlxtend/docs/sources/` (optional)
- [x] Checked that the Travis-CI build passed at https://travis-ci.org/rasbt/mlxtend

### CODE REVIEW

**Comment by bbardakk** [comment]
Finally, all checks have passed! Now, I think that we can discuss on the implementation. Could you please give me a feedback about the implementation @rasbt ?

**Comment by rasbt** [comment]
Looks cool so far!  

- one thing I noticed: could you change the  you change the positive label to 1; it's the default label in scikit-learn as well and thus probably less confusion

I found another example for computing lift scores on classification examples:

screen shot 2016-12-20 at 12 04 11 am

(from http://www.cs.cornell.edu/courses/cs578/2003fa/performance_measures.pdf)

and I tried to use your lift implementation to see if I can get the same results. I.e., on the following two arrays

    y_target =    np.array([0, 0, 1, 0, 0, 1, 1, 1, 1, 1])
    y_predicted = np.array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0])

I would come up with the following confusion matrix:

unknown

and then computing the following

    a = 3
    b = 1
    c = 4
    d = 2

    (a/(a+b)) / ((a+c)/(a+b+c+d))

I got 1.0714285714285714, the result I get when I set your positive label to 1.

So I think your positive label got flipped between 0 and 1 if this example above is correct. Do you have another example from literature (or another tool) as a reference? Would be useful to use those for the unit tests. Also, it would be nice if you could add a short docstring for the support function and maybe some unit tests as well. No hurry though, and thanks for contributing! :)

**Comment by bbardakk** [comment]
Hi Sebastian @rabst,

Firstly, thanks for your fast feedback. I added small docstring and unittest for support method. Also added additional unittest to lift metric. I changed the positive label default value 0 to 1.

So, if binary parameter is true and positive label is 1:

```
[0,0,1,1,2,4] changes to [0,0,1,1,0,0]
```
if binary parameter is true and positive label is 0:
```
[0,0,1,1,2,4] changes to [1,1,0,0,0,0]
```

In your comment, you provide an example but your confusion matrix and the upper confusion matrix(which is inside of the referenced slide) axis values are different. So I think that if we have y_target and y_pred like in below: 

```
y_target =    np.array([0, 0, 1, 0, 0, 1, 1, 1, 1, 1])
y_predicted = np.array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0])
```

our a, b, c and d values are like here:
```
a = 2
b = 4
c = 1
d = 3
```

When we calculate lift score with formula in that slide :
```
a/(a+b) / (a+c)/(a+b+c+d)
2/6 / 3/10 = 1.111111
```
and the calculation with our implementation:
```
lift_score(y_targ, y_pred, binary=True, positive_label=1)
support(y_targ, ypred) / ( support(y_targ) * support(y_pred))
= 0.2 / (0.6 * 0.3) = 1.111111
```

Another detailed example is given in the below:

```
market.csv
Transactions |	  Apple		| 	 Milk	|	 Beer	|	Pear	|	Rice	|
transaction1 |   	1		|	  0		|	  1		|	 0		|	 1		|
transaction2 |   	1		|	  0		|	  1		|	 0		|	 1	 	|
transaction3 |   	1		|     0		|	  1		|	 0		|	 0		|
transaction4 |   	1		|     0		|	  0		|	 1		|	 0		|
transaction5 |   	0		|     1		|	  1		|	 0		|	 1		|
transaction6 |   	0		|     1		|	  1		|	 0		|	 1		|
transaction7 |   	0		|     1		|	  1		|	 0		|	 0		|
transaction8 |   	0		|     1		|     0		|	 1		|	 0		|
```

```python
import pandas as pd
import numpy as np
from mlxtend.evaluate import lift_score

df = pd.read_csv("market.csv", index_col="Transactions")

apple = np.asarray(df['Apple'])
milk = np.asarray(df['Milk'])
beer = np.asarray(df['Beer'])
pear = np.asarray(df['Pear'])
rice = np.asarray(df['Rice'])


def result_equality(y_targ, y_pred):
	cm = confusion_matrix(y_target=y_targ,y_predicted=y_pred)
	a = cm[-1, -1]
	b = cm[0, -1]
	c = cm[-1, 0]
	d = cm[0, 0]
	formula = ( a / float(a+b)) / float((a+c) / float(a+b+c+d))
	if lift_score(y_targ, y_pred) == formula:
		print ("equal")
	else:
		print ("not equal")


result_equality(apple, milk) # equal
result_equality(apple, beer) # equal
result_equality(beer, rice) # equal
```

References:

[Ref1](http://michael.hahsler.net/research/association_rules/measures.html#lift)

[Ref2](http://www.kdnuggets.com/2016/04/association-rules-apriori-algorithm-tutorial.html)

[Ref3](https://education.emc.com/DSBook/)

**Comment by rasbt** [comment]
Thanks for the update! 

> In your comment, you provide an example but your confusion matrix and the upper confusion matrix(which is inside of the referenced slide) axis values are different.

Yeah, I computed that with the positive label=0 to compare it to your lift function. If the positive label is 1, like you said, the confusion matrix should be transposed to match the one in the upper figure (resulting in a lift 1.11111, which I previously got when I had your positive label set to 0, but I was maybe mistaken). Now, I got the right results matching your `lift_score` function :)

```
a = 2
b = 4
c = 1
d = 3

(a/(a+b)) / ((a+c)/(a+b+c+d))
```
1.11111...



Thanks for the references. I think adding a short sentence to the docstring instead docstring would be nice, something like 

> Lift measures how many times more often X and Y
 occur together than expected if they where statistically independent. A lift value of 1 indicates independence between X and Y.
 
but with a meaning rephrased to predictive models. Adding `Range: [0,\infty]` in the docstring for the `Returns` section would also be helpful to know what expect. I got the `Range: [0, \infty]` from the reference you listed, but I think that's mathematically not correct and should be  `Range: [0, \infty)` when I remember correctly from calculus classes :P.

So what I have in mind is 


```  Returns
     ----------
     score : float
         Lift score in the range [0, \infty)
```

and for support:

```  Returns
     ----------
     score : float
         Support score in the range [0, 1]
```

Do you have an idea for a short, descriptive docstring for lift and support? I have to think a bit about this :P

Also, for the user documentation, I am happy to help and set this up if you like; this part is probably a bit tricky with the mkdocs stuff :P. If you have the "allow maintainers ..." features enabled in this PR, I am happy to add it here. 
allow-maintainers-to-make-edits-sidebar-checkbox

**Comment by bbardakk** [comment]
I change the return type description in docstring for both support and lift metric.

I think that we can use below description for lift score in this [link](https://docs.oracle.com/database/122/DMCON/classification.htm#DMCON035).

```
Lift measures the degree to which the predictions of a classification model are better than randomly-generated predictions. 
```

For the support, it is obviously not the best but maybe:
```
Fraction of the true value(?) in predictions and target values.
```

After agreeing on the descriptions, I will change that parts.

Also, _allow edits from maintenance button_ seems checked from my side. In the preparing of user documentation step, should I do anything, or will you handle that part ? Could you please inform me about that :)

**Comment by rasbt** [comment]
Thanks again for the update! It's a pretty busy pre-XMas time but I will try to provide comments in the next few days; just wanted to let you know! 

> Also, allow edits from maintenance button seems checked from my side. In the preparing of user documentation step, should I do anything, or will you handle that part? Could you please inform me about that :)

I can put together a documentation draft and I would push it to your branch then so that you can take a look :)

**Comment by bbardakk** [comment]
Okay Sebastian, I look forward to hearing from you and happy new year:)

**Comment by rasbt** [comment]
Hi, @bbardakk 

sorry about the very, very late follow-up on this! I had so many things on my todo list on January that I completely lost track. I just added the documentation, and I see that there's a merge conflict now -- probably due other changes I made to mlxtend that I made in the mean time. 

I will try to resolve these and merge your PR since I wanted to make a new version for `pip` that includes the most recent bug fixes. You implementation is really nice, and thanks again for the great contribution. Also, if you have any feedback on the documentation, please feel free to make suggestions or improvements :).

**Comment by bbardakk** [comment]
Hi, **@rasbt**

I am very happy about merging my pr, and I hope it will useful for users. I have been using mlxtend for a while and I will try to give feedback about the documentation or other things. Also, when I have a free time I want to contribute to some another issues :)

Thank you for building a very useful library like this. Have a nice day.

All the best,

Batu

**Pull request merged**
