### PR TITLE
Sklearn0.18

### PR DESCRIPTION
**Pull request by avloss**
### Description

adding an estimator not fitted exception to ensemble vote

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks for cleaning up the submission! What's your opinion on handling the sklearn 0.17 vs 0.18 issue here. Except for the `NotFittedError` the code is fully compatible to sklearn 0.17. I am a bit hesitant to enforce sklearn 0.18 just yet since some people may have not upgraded it yet. On the other hand, I think switching to and requiring sklearn 0.18 would be reasonable for such a small open-source project. 

I would like to add a message about sklearn 0.18 to the docs though, setting up an "requirements" section in the installation section and add a note to the Changelog to avoid potential confusion before merging. 

Also, the travis config file needs to be changed to 0.18 then.

I can totally do that if you don't mind; maybe it's easiest if you could allow me to make the appropriate changes to this pull request, e.g., via the "allow edits from maintainers" box

allow-maintainers-to-make-edits-sidebar-checkbox

https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by avloss** [comment]
yes, that box is checked, please feel free to do whatever you feel appropriate with this PR. I've simply done this to "try the waters" - PR it's only few lines long! I feel like you are giving this too much attention! :) great library BTW! thanks for making this public - I've learned a lot when going through your docs!

**Comment by rasbt** [comment]
> yes, that box is checked, please feel free to do whatever you feel appropriate with this PR. I've simply done this to "try the waters" - PR it's only few lines long! I feel like you are giving this too much attention! :) great library BTW! thanks for making this public - I've learned a lot when going through your docs!

Thanks! I haven't used this "new" collaboration feature; this PR would be a good guinea pig ;). I think I will make a "release version" with scikit-learn 0.17 support first though, and add a message that the next version will require sklearn 0.18 and then modify and merge this PR :)

**Comment by rasbt** [comment]
Hey, Anton,
it's been some time since you opened this PR. I added sklearn 0.18 a while back, and I rebased this fork and added a little message to the changelog. Thanks again for the contrib. Will merge once the CI tests pass.

**Pull request merged**
