### PR TITLE
Implement drop proba col

### PR DESCRIPTION
**Pull request by rchaves33**
### Description

Replace `drop_last_proba` with `drop_proba_col` in `StackingClassifier` and `StackingCVClassifier`.

### Related issues or pull requests

Implements #590.

### Pull Request Checklist

- [X] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [X] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [X] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [X] Ran `PYTHONPATH='.' pytest ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `PYTHONPATH='.' pytest ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [X] Checked for style issues by running `flake8 ./mlxtend`

### CODE REVIEW

**Comment by rchaves33** [comment]
I implemented your suggestion @bmreiniger. Could you please review to see if this is what you intended?

@rasbt Travis is throwing two errors, but they appear unrelated to any code I've changed.

**Comment by bmreiniger** [comment]
> I implemented your suggestion @bmreiniger. Could you please review to see if this is what you intended?

Yep, this looks to be what was intended.

**Comment by rasbt** [comment]
Thanks for the PR! I am currently a bit swamped by all the responsibilities working and teaching from home, but I will take a look at this soon! 

Regarding the Travis errors, you are right, they are unrelated. The dlib downloads (which are used for facial keypoint detection in another part of the library) are super slow right now, which is why the tests seem to fail. I just modified the documentation-generating code and unit tests such that this part is excluded from Travis for now. It seems to be working. Let me rebase your PR based on these fixes.

**Comment by rasbt** [comment]
arg the rebase faild for some reason. Let me revert this.

**Comment by rasbt** [comment]
Added one more check

**Comment by rasbt** [comment]
looks good to merge now. Thanks for the PR!

**Pull request merged**
