### PR TITLE
add groups parameter to SFS and EFS fit(), for forwarding to sklearn cv

### PR DESCRIPTION
**Pull request by arc12**
### Description
Add `groups` as parameter to fit() method of `SequentialFeatureSelector` and `ExhaustiveFeatureSelector` for forwarding to sklearn cross-validator fit() methods. e.g. for GroupKFold

Added unit tests to match.

### Related issues or pull requests
Issue #524 proposed this feature

### Pull Request Checklist
- Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable).
-  Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- Ran `nosetests ./mlxtend -sv` and make sure that all unit tests pass (done for feature selection)
- flake8 applied to changes made in this PR (I noted flake8 detects multiple _existing_ issues, at least using my standard flake8 config)

Not done (presumed not necessary)
- Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)

### CODE REVIEW

**Comment by arc12** [comment]
I see some pep8 line length complaints; I missed these as we've long since moved to 160 chars and have flake8 config to match.
If this is important, please kick it back to me and I'll amend.

**Comment by rasbt** [comment]
Thanks for the PR!

> Not done (presumed not necessary)
> Modify documentation in the corresponding Jupyter Notebook under mlxtend/docs/sources/

The docstring gets loaded in the last cell of the notebook, which then gets converted to HTML documentation during the next version release. So, it's probably not necessary to modify anything at this stage, indeed. However, it would be good to check whether the code examples still all work due to the addition to `groups` -- maybe there was an example that relied on fit_params or so.

> I see some pep8 line length complaints; I missed these as we've long since moved to 160 chars and have flake8 config to match.
If this is important, please kick it back to me and I'll amend.

PEP8 compliance is not crucial but I decided to adopt it as a guideline here some time ago so that the code doesn't become too heterogenous over time. Would be nice if you could break these lines into two to meet the 79 char.

**Comment by rasbt** [comment]
Was just going through the PR, looks great. Thanks a lot! (Along the way, I also made the pep8 changes; so once the tests pass, it should be good to merge!)

Thanks!

**Comment by arc12** [comment]
great, thanks!
sorry I didnt get around to pep8 tidy.

**Pull request merged**
